security:
  sessions: if-required

spring:
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${doorje.datasource.url}
    username: ${doorje.datasource.username}
    password: ${doorje.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/
      
logging:
  level:
    org.springframework.security: DEBUG
