eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ture
      routes:
        - id: doorje
          uri: lb://doorje-service
          predicates:
          - Path=/doorje/**
        - id: root
          uri: no://op
          predicates:
          - Path=/
          
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enable: true
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 60000
           
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
