eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/
      
security:
  oauth2:
    client:
      accessTokenUri: ${doorje.oauth.token.uri}
      userAuthorizationUri: ${doorje.oauth.authorization.uri}
      clientId: ${doorje.oauth.client.id}
      clientSecret: ${doorje.oauth.client.secret}
    resource:
      userInfoUri: ${doorje.oauth.userinfo.uri}
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ture
      routes:
        - id: doorje
          uri: lb://doorje-service
          predicates:
          - Path=/doorje/**
        - id: root
          uri: no://op
          predicates:
          - Path=/
          
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 60000
           
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE
