spring:
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${doorje.datasource.url}
    username: ${doorje.datasource.username}
    password: ${doorje.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

zuul:
  ignoredServices: "*"
  routes:  
    doorje:
      path: /doorje/**
      serviceId: doorje-service
      
proxy:
  auth:
    routes:
      doorje: oauth2

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/
      
security:
  sessions: ALWAYS
  oauth2:
    client:
      accessTokenUri: ${doorje.oauth.token.uri}
      userAuthorizationUri: ${doorje.oauth.authorization.uri}
      clientId: ${doorje.oauth.client.id}
      clientSecret: ${doorje.oauth.client.secret}
    resource:
      userInfoUri: ${doorje.oauth.userinfo.uri}
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
        
ribbon:
  eureka:
    enable: true
  SocketTimeout: 100000
  ReadTimeout: 100000
