spring:
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${doorje.datasource.url}
    username: ${doorje.datasource.username}
    password: ${doorje.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

zuul:
  ignoredServices: "*"
  routes:  
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: doorje-uaa
      stripPrefix: true
    doorje:
      path: /doorje/**
      serviceId: doorje-service
      stripPrefix: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/
      
security:
  oauth2:
    client:
      accessTokenUri: ${doorje.oauth.token.uri}
      userAuthorizationUri: ${doorje.oauth.authorization.uri}
      clientAuthenticationScheme: form
    resource:
      userInfoUri: ${doorje.oauth.userinfo.uri}
      preferTokenInfo: false  
  sessions: ALWAYS
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
        
ribbon:
  eureka:
    enable: true
  SocketTimeout: 100000
  ReadTimeout: 100000
