spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${doorje.datasource.url}
    username: ${doorje.datasource.username}
    password: ${doorje.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${doorje.eureka.uri}/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  eureka:
    enable: true
  SocketTimeout: 100000
  ReadTimeout: 100000
